#!/usr/bin/env bash

git clone https://github.com/neovim/neovim ~/personal/neovim

sudo apt-get install ninja-build gettext cmake curl build-essential

cd ~/personal/neovim

make CMAKE_BUILD_TYPE=RelWithDebInfo 

sudo make install
